# Generated by Django 3.2 on 2021-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('postal_code', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
