# Generated by Django 3.2 on 2021-05-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210511_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address is already in use.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
