# Generated by Django 3.2 on 2021-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210512_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card', models.CharField(max_length=19)),
                ('cvc', models.PositiveSmallIntegerField()),
                ('expiry', models.DateField()),
            ],
        ),
    ]
