# Generated by Django 3.2 on 2021-05-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_picture'),
        ('user', '0007_creditcard'),
    ]

    operations = [
    ]
